### ISSUE TITLE
Very slow in CSS files with base64-encoded fonts

### ISSUE THREAD

**Issue by chrisgrieser** [emmetio/sublime-text-plugin#177]
I have a larger CSS files which contains a few base64-encoded fonts. (the css file is ~800kb of which 650kb are the fonts). I noticed a *considerable* slowdown, similar to what has previously been described in #143. 

I tested removing all base64 fonts, and Emmet is blazingly fast. For context, I used a fresh install of the plugin, without any changes to the configuration in `Emmet.sublime-settings` (setting `auto_mark` to false also didn't result in any noticeable speedup).

Not sure about how exactly Emmet works, but considering the format, would it maybe be possible for emmet to simply ignore things base64-encoded lines? (or all of `@font-face`, if that's easier to implement?)

```css
@font-face {
	font-family: "iA Writer Quattro S";
	font-weight: 700;
	font-style: normal;
	font-display: swap;
	src:
            url("data:font/woff2;charset=utf-8;base64,d09GMgABAAAA....")
            format("woff2");
}
```
